# Cloudflare Worker 配置文件

name = "wechat-customer-service"
main = "index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
name = "wechat-customer-service"
# 微信企业号配置
WECHAT_CORP_ID="ww752595c63c2bbbae"
WECHAT_KF_SECRET="11"
WECHAT_KF_TOKEN="afI0vH"
WECHAT_KF_ENCODING_AES_KEY="JgONjY548yueHIkioLsxdVmVRe4JkNYRiJWBvqrBpM2"

# 加密服务配置（由于 CF Worker CRYPTO 兼容性问题，需要单独部署）
CRYPTO_SERVICE_URL="https://yourexample.workers.dev/callback"

# OpenAI API 配置
OPENAI_API_KEY="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"
OPENAI_BASE_URL="https://openrouter.ai/api/v1/"
OPENAI_MODEL="deepseek-chat-v3.1:free"
OPENAI_TIMEOUT=30000
# OPENAI_ORGANIZATION=org-your-org-id
# OPENAI_PROJECT=proj-your-project-id

# 系统提示词配置
SYSTEM_PROMPT="your are helpful assistant, reply in chinese, and reply in plain text format, text length should be less than 10240 characters" 


# KV存储配置（用于持久化对话历史）
[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "ecfbbd3e719b4b5e9b591191276f6d36"
preview_id = ""

# KV存储配置（用于消息处理状态跟踪）
[[kv_namespaces]]
binding = "MESSAGE_TRACKER"
id = "2f4f23e512cd41e887815c0d8c6bf464"
preview_id = ""